<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Role in Company_zZVKA</name>
   <tag></tag>
   <elementGuidId>d2936985-9ac5-4ce8-8a92-42e23445c768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zZVKA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zZVKA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79e24fe-8ef4-462a-90b9-10da85740bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelRole</value>
      <webElementGuid>8893b677-6476-4f73-9325-598d2d0bd078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zZVKA</value>
      <webElementGuid>334eba39-0b93-40da-affb-8a78c07fa0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zZVKA</value>
      <webElementGuid>e71ad7b5-8e42-4c90-b972-c70fc0291522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6ec62b89-fa5f-4496-8ebf-52c384858dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zZVKA&quot;)</value>
      <webElementGuid>c9d3cc00-676d-4a27-a981-0ee50b6fc118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zZVKA']</value>
      <webElementGuid>49c1344a-1e39-42c5-8790-d34f61e0d0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input[1]</value>
      <webElementGuid>871e3385-c49a-4c4f-9eb4-cc0d573015e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::input[2]</value>
      <webElementGuid>d306242f-49e3-4a82-8360-ccfd99643658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::input[1]</value>
      <webElementGuid>cd9cc3b0-f7ab-42a3-b52f-6ebde58505d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::input[2]</value>
      <webElementGuid>2e9d5392-b0d2-4c32-850e-bcd8f379a288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/rpa1-field/div/input</value>
      <webElementGuid>e72f2424-78e3-41e1-86b4-2f749b8eb337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zZVKA' and @name = 'zZVKA']</value>
      <webElementGuid>0e7dcef9-ec7d-42c3-9ced-adabf8d6272f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
