<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_XVJDc</name>
   <tag></tag>
   <elementGuidId>7a22085e-a12e-4d7f-bf91-3ce07e39b935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#XVJDc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='XVJDc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e016ae4b-a26d-414f-b8f4-7be862a08d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelPhone</value>
      <webElementGuid>c7412525-e781-48ee-b6f3-ccf226fa9c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>XVJDc</value>
      <webElementGuid>e0fc1f70-eb63-4ec2-8773-f310f77b8440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>XVJDc</value>
      <webElementGuid>478fa88c-dae1-458f-a37a-780a4f94fde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0cd1636a-b6d1-449f-8bcd-d7faf0b72427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;XVJDc&quot;)</value>
      <webElementGuid>2962fe31-a396-48d9-99a7-d9a8d00a3ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='XVJDc']</value>
      <webElementGuid>9d119694-f3df-4f40-9705-d524c46327de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::input[1]</value>
      <webElementGuid>e4737dd6-dc6b-431d-aa6e-85c46ac69c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input[2]</value>
      <webElementGuid>424254a0-b009-400d-b027-4767b9dd5f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/preceding::input[1]</value>
      <webElementGuid>d63ec53c-e99c-418f-aaf0-393a163d5343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/preceding::input[2]</value>
      <webElementGuid>15268cca-63c3-429c-8493-581ace73293c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/rpa1-field/div/input</value>
      <webElementGuid>26eedaf4-937f-47cd-bb70-2765739806d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'XVJDc' and @name = 'XVJDc']</value>
      <webElementGuid>161ec37c-0368-4daa-a658-6618dee170d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
