<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_zxS5R</name>
   <tag></tag>
   <elementGuidId>2fe51396-df86-49aa-9528-0ceff8ef5e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zxS5R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zxS5R']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06227364-3909-4508-83c4-38cdb41a2dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelLastName</value>
      <webElementGuid>edf6c927-3e90-45c8-ab13-16d6427e7b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zxS5R</value>
      <webElementGuid>fe206aa8-ca02-423e-8603-c07b21e1f54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zxS5R</value>
      <webElementGuid>3eb1652a-3eed-4c3d-8b3c-2e03083eb616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7bcfeddb-9103-4cc3-b14d-dcd1b2b64485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zxS5R&quot;)</value>
      <webElementGuid>1ff49670-10bc-4d10-8452-72975d4e0840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zxS5R']</value>
      <webElementGuid>e2026ba2-b33b-4ad4-9ab8-5f98ba1f12ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::input[1]</value>
      <webElementGuid>ef6e4b7d-bede-498b-a150-a9cac80a7779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input[2]</value>
      <webElementGuid>f7f8f997-8817-4d17-9c0c-2cecb76253e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::input[1]</value>
      <webElementGuid>fd407214-454f-4910-8140-80bde3389718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::input[2]</value>
      <webElementGuid>e782cbe1-4a28-4db5-9036-8ab1f83fe136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/rpa1-field/div/input</value>
      <webElementGuid>06978f00-d033-43f1-860c-fa3932c99ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zxS5R' and @name = 'zxS5R']</value>
      <webElementGuid>32a90762-8bae-4c36-aff8-0fedfb079683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
