<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_1ODde</name>
   <tag></tag>
   <elementGuidId>008d4073-6fca-4d11-83e6-e43ac6924c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1ODde</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1ODde']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b836aa0-f60c-4c73-8f8c-4b552e7bcee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelAddress</value>
      <webElementGuid>2b7ce247-e283-4492-8937-47fd26f12bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1ODde</value>
      <webElementGuid>16c59cc3-fd2d-480f-94cd-a72d4d5eeb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1ODde</value>
      <webElementGuid>84025c51-49bc-4c9a-a5e8-3de1c8671ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9972a944-09bc-43c2-95cd-254e0f78d9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1ODde&quot;)</value>
      <webElementGuid>b922d5c8-e446-447f-bed5-01bb5dce4e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1ODde']</value>
      <webElementGuid>6329cd8d-743b-4a48-9868-035ffd09ddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::input[1]</value>
      <webElementGuid>44d25f28-9a44-412d-bf8e-0455d75b9c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input[2]</value>
      <webElementGuid>2b5853a8-e434-490d-b22a-374b0b190018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1ODde', '&quot;', ')')])[1]/preceding::input[2]</value>
      <webElementGuid>84879748-82de-4550-b5f9-5aba64b82ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/rpa1-field/div/input</value>
      <webElementGuid>6a91b549-0b13-49c7-99a0-fafa021836d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1ODde' and @name = '1ODde']</value>
      <webElementGuid>e0b72bd1-2870-4db7-a89a-0161eba29635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
