<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_9FFQ8</name>
   <tag></tag>
   <elementGuidId>d1ffa530-ce1c-4b62-aee8-c0d4fcc6e42b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9FFQ8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9FFQ8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06d37e77-a753-454f-8c47-3e720ecb2c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelCompanyName</value>
      <webElementGuid>b9dacac6-b0d5-4a15-ac4a-b7b13fd8d7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9FFQ8</value>
      <webElementGuid>239fed65-ff32-4902-a96e-61fd92c5c75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9FFQ8</value>
      <webElementGuid>d96ac1bf-5e56-4989-8ae7-9fe7a33fee9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>48d5cf11-9bb2-4345-9cc3-d038fd67b31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9FFQ8&quot;)</value>
      <webElementGuid>bcf78625-0395-4b95-8920-9441e666a4ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9FFQ8']</value>
      <webElementGuid>9d4f6eb1-6dab-4857-8820-1f5f026fd614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::input[1]</value>
      <webElementGuid>362b04b9-3420-4550-9bb0-4a9cb35f9c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round 1'])[1]/following::input[1]</value>
      <webElementGuid>909d0c68-a3ea-4012-84ac-c5b0dfdf9c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::input[1]</value>
      <webElementGuid>6afb8aed-d516-450e-b935-f0556ac9c305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::input[2]</value>
      <webElementGuid>0b1b5c69-b664-4818-9d8c-a208b5dc8d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>29708725-1a4c-4ac7-8718-21a32c66aa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9FFQ8' and @name = '9FFQ8']</value>
      <webElementGuid>36be9c61-65ac-4d8a-91ca-65aade0baf9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
