<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_WnRFK</name>
   <tag></tag>
   <elementGuidId>c3ad1fb2-1011-4251-bb0b-f45a8c62054c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WnRFK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WnRFK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37abed81-a840-4b52-b7aa-7997bb72ac5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelFirstName</value>
      <webElementGuid>e548d954-249d-4d2b-8f88-d6187c8ae7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WnRFK</value>
      <webElementGuid>153d2d0f-8b1e-4ccd-8259-e782c99ca8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WnRFK</value>
      <webElementGuid>c6d56646-a34e-4c4e-8762-cdda0cf8adbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ee68451c-8a03-4f09-a863-bdb788613e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WnRFK&quot;)</value>
      <webElementGuid>9743f1b8-bcb9-4b32-8f1d-ab72dacb960e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WnRFK']</value>
      <webElementGuid>cda669d1-7975-4a17-a643-e2a72cbcf630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input[1]</value>
      <webElementGuid>88f8026f-7d12-4f66-9f6e-76d5774bf8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input[2]</value>
      <webElementGuid>41a80947-faf8-48ea-92a9-1af0d5b36cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::input[1]</value>
      <webElementGuid>58903f77-f3a7-4917-8ea4-4e04fb491bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'WnRFK', '&quot;', ')')])[1]/preceding::input[3]</value>
      <webElementGuid>8b7fd06e-93e0-4504-b639-66504e90df49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/rpa1-field/div/input</value>
      <webElementGuid>16357cd6-7df2-45df-8ac4-f53474a98a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WnRFK' and @name = 'WnRFK']</value>
      <webElementGuid>9acf9eb4-123e-4e08-9351-edf41542e75b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
