<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_onpDZ</name>
   <tag></tag>
   <elementGuidId>8748105a-44b1-4049-94bd-5f81072a0319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onpDZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onpDZ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dd40f54-1229-4f4b-9003-218b7fff74cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelAddress</value>
      <webElementGuid>84a32762-a864-449b-baa9-adf31cec833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onpDZ</value>
      <webElementGuid>64720218-9f93-4339-8f62-2179c9b5df3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onpDZ</value>
      <webElementGuid>8b2e7fd0-9299-41c3-b66d-6eab2dba2422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ae1d4c85-d824-4ec5-9a2a-a5f99e24993b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onpDZ&quot;)</value>
      <webElementGuid>e0eba3e3-5e1e-4e74-b203-93069375a9b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onpDZ']</value>
      <webElementGuid>150ee30a-16a9-4e9a-b69f-0289add4fc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::input[1]</value>
      <webElementGuid>3af1d0ab-2173-496f-9459-1da22056fb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::input[2]</value>
      <webElementGuid>458ffdfd-b8b5-4015-b52e-1abcb1786c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::input[1]</value>
      <webElementGuid>f6204325-96c6-45e9-86b3-e746791286d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'onpDZ', '&quot;', ')')])[1]/preceding::input[3]</value>
      <webElementGuid>b21750d2-07aa-4007-bbac-bb969b31fc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/rpa1-field/div/input</value>
      <webElementGuid>1bd31009-ba43-42f7-93e1-023a2db805f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'onpDZ' and @name = 'onpDZ']</value>
      <webElementGuid>4a6daa33-7e3f-4c36-bd45-542ec9db214a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
