<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_7r1MI</name>
   <tag></tag>
   <elementGuidId>1f927a4e-1ae2-4e64-a3b6-3ee0e0c5cf9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7r1MI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7r1MI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>736b4b77-29f2-426b-8e69-96bec2f332ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelLastName</value>
      <webElementGuid>12e91e1f-aa6e-4558-90f9-202f6f4a537b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7r1MI</value>
      <webElementGuid>15ce8c41-e7b6-46b1-9a92-0da18ee75c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>7r1MI</value>
      <webElementGuid>26ed7a31-208d-4fbe-84e6-58c62cadefce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6eca4e14-cdfb-4257-8928-974622d1adbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7r1MI&quot;)</value>
      <webElementGuid>d0aef0a9-2efe-4d6e-a1ec-fcfafc98275c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7r1MI']</value>
      <webElementGuid>8fa805a0-af14-4d72-8b9a-dc90166f57fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::input[1]</value>
      <webElementGuid>4846ef2c-98d8-4bdf-86ba-5bd2e6b09e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::input[2]</value>
      <webElementGuid>ec1e7f66-e054-4138-aa2b-0a82acd95f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/preceding::input[1]</value>
      <webElementGuid>6386a479-4037-4ea2-91b3-a9727eb7e3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::input[2]</value>
      <webElementGuid>c92695d0-71f2-4dc6-94e6-b1623cfd7b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/rpa1-field/div/input</value>
      <webElementGuid>a0b203ca-5569-4273-8a24-bf81cd10d37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7r1MI' and @name = '7r1MI']</value>
      <webElementGuid>bb7f75a1-793d-4109-b9e2-f8e1ec0e249b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
