<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_9k5HD</name>
   <tag></tag>
   <elementGuidId>f94e7e6f-9b31-49d2-a069-e4279779e28a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9k5HD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9k5HD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23b1b3e1-9d93-47e0-9f3b-ad2c56a42459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelEmail</value>
      <webElementGuid>c2d159d3-b518-42c5-bdea-5cebb02b5731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9k5HD</value>
      <webElementGuid>9f8e524e-33a4-4b10-936f-3153a38dc49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9k5HD</value>
      <webElementGuid>e5755184-9117-4754-84d8-7ea82fb86959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>16e87678-722e-4cdf-a73c-71926e4ca7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9k5HD&quot;)</value>
      <webElementGuid>0be89c4a-cd43-4841-ab35-8720292fa77c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9k5HD']</value>
      <webElementGuid>823766b0-eef5-4bd3-9324-346fe3a5a3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::input[1]</value>
      <webElementGuid>54cd1927-e5e4-4bc4-bfc2-15c5a1bbf34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::input[2]</value>
      <webElementGuid>03ef4711-a130-4835-b2d6-9f8f9cc9ffb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '9k5HD', '&quot;', ')')])[1]/preceding::input[2]</value>
      <webElementGuid>72865c4b-0d06-48fb-82ff-1d661123a69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/rpa1-field/div/input</value>
      <webElementGuid>be4027e8-66ec-45f7-affa-f5b538c5f6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9k5HD' and @name = '9k5HD']</value>
      <webElementGuid>c440ca4b-1f34-4834-b128-0366a75e497a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
