<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_WCJfs</name>
   <tag></tag>
   <elementGuidId>e1e7e74c-3c5b-4a68-afb3-c74af2cba69a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WCJfs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WCJfs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87f92574-3c04-4582-bf4d-222ea5aa9134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelEmail</value>
      <webElementGuid>71c3b6ab-516b-4a31-9bfc-ed0589c4a4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WCJfs</value>
      <webElementGuid>233a9f4d-5bb9-4f26-b1e3-687f1bd97b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WCJfs</value>
      <webElementGuid>80cb690c-fa6a-428e-aaf5-b5363eca5b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2cc6a77e-0b28-4093-88b3-768db20d5f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WCJfs&quot;)</value>
      <webElementGuid>bd0b8c68-6a95-4933-a116-0cad9422a1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WCJfs']</value>
      <webElementGuid>7f4bb0e6-aefc-4db5-a7bc-c14fa2839952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::input[1]</value>
      <webElementGuid>21d7d87b-6e15-4480-a7ab-0f3171b9dc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::input[2]</value>
      <webElementGuid>f230598d-ee75-45ee-8050-59d51ada4642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::input[1]</value>
      <webElementGuid>fffa044b-b27a-4d4e-ad40-5e227c29fa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/preceding::input[2]</value>
      <webElementGuid>0cc338ed-74e7-4274-8b1f-e7f25a248241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/rpa1-field/div/input</value>
      <webElementGuid>079573e7-28eb-4d05-aef5-6f57e8d29724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WCJfs' and @name = 'WCJfs']</value>
      <webElementGuid>057ad7b8-a472-4e3c-aabe-85ee4362805e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
