<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Role in Company_PKNbi</name>
   <tag></tag>
   <elementGuidId>4451f74c-2fd1-4864-afd2-87eeedc82271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PKNbi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PKNbi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>899b8a5a-9c86-4ce7-8a98-23ed78c5d76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelRole</value>
      <webElementGuid>da99ec9c-9b69-46cc-a978-f0074a75191f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PKNbi</value>
      <webElementGuid>11102ac3-b75b-4957-ad43-e411b09c94fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PKNbi</value>
      <webElementGuid>9eff9857-e19c-4b86-ad99-7f0b3c305051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>64d954b5-be3d-4d47-b554-0bfcacfac324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PKNbi&quot;)</value>
      <webElementGuid>4e9ae7d7-5946-4af8-abec-755b97d98955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PKNbi']</value>
      <webElementGuid>4eaed703-f9e9-4440-9104-403bff644da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input[1]</value>
      <webElementGuid>4fcc4386-01e7-429b-a388-9ea07a5265cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::input[2]</value>
      <webElementGuid>003c7e71-ba80-48d4-a381-65ec4beca644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::input[1]</value>
      <webElementGuid>8451d754-194a-4898-aa9d-2c8fa26d70c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::input[2]</value>
      <webElementGuid>f76b318a-ed7d-4e48-a06a-6ef5baa61288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/rpa1-field/div/input</value>
      <webElementGuid>5f316163-1e56-42d8-af41-caa1d6bddca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PKNbi' and @name = 'PKNbi']</value>
      <webElementGuid>ec6566c7-f981-439f-8c2f-f40d9ceb644c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
