<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_m483r</name>
   <tag></tag>
   <elementGuidId>4db4c02e-b68b-48da-9b72-a118d67e0f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m483r</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='m483r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17558a32-cf35-4b91-99d0-fb6bd5dd1bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelCompanyName</value>
      <webElementGuid>32b705f6-fc68-4a53-932f-1cd5f539a40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m483r</value>
      <webElementGuid>497d0629-7aa9-4157-8f41-f2f9a373b474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>m483r</value>
      <webElementGuid>3b3a3b43-9ef9-4db6-8712-6518f8d538c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c10e42f9-d6ee-4053-8cd6-4a969028ab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m483r&quot;)</value>
      <webElementGuid>2d5072d7-5fc9-40b8-acd3-8d48238dc2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='m483r']</value>
      <webElementGuid>3423071c-76b7-40fc-9bf8-d237fa634e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::input[1]</value>
      <webElementGuid>bb1b2dcf-629e-41aa-9c63-bcd532e74f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::input[2]</value>
      <webElementGuid>015cb068-1f58-49e5-b06f-03187ed3cc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/preceding::input[1]</value>
      <webElementGuid>34f64304-5869-4fd9-86f8-e6c9fd2daa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::input[2]</value>
      <webElementGuid>55d5cb4b-3fb8-4c5f-8ad1-4a65dbf874a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/rpa1-field/div/input</value>
      <webElementGuid>81ba15ed-351c-42aa-a7eb-78b26864abe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'm483r' and @name = 'm483r']</value>
      <webElementGuid>fc5f8d02-ff02-4aad-bea5-7f2f3e10463e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
