<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_B0ryq</name>
   <tag></tag>
   <elementGuidId>663d9ea4-32be-453f-8b8c-33e3da63b094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B0ryq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='B0ryq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0370fcff-80a7-4dbc-b2fb-ced07483b0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelFirstName</value>
      <webElementGuid>50ebfeae-7724-4e53-bb2a-6c4fd4b2be0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B0ryq</value>
      <webElementGuid>a28230f3-1fc7-434c-89ac-d132b1dba472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>B0ryq</value>
      <webElementGuid>5359f645-c91f-4b24-a10d-8815ff7ae52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9dd4fd80-296c-462b-b9fb-b5b87513a880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B0ryq&quot;)</value>
      <webElementGuid>aaac3658-72c3-4d6c-a892-0432776b35c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='B0ryq']</value>
      <webElementGuid>4d4af44c-34e6-474e-b2fe-47db0477148b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input[1]</value>
      <webElementGuid>d7ac9f93-13d2-4b23-9b48-67c4f6a59b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round 2'])[1]/following::input[1]</value>
      <webElementGuid>fd3c05dd-280c-4758-a787-4b7a148ed1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::input[1]</value>
      <webElementGuid>7a521d5f-e37e-45d4-b1bc-8ba15a63c745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/preceding::input[2]</value>
      <webElementGuid>968b871a-1151-4981-aa51-bef28e16534b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>258cb520-e2f3-46b8-8915-873a86a487b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'B0ryq' and @name = 'B0ryq']</value>
      <webElementGuid>a1a51809-ab6f-4c5b-a0de-a4c56dd4ee0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
